server:
  port: 8000
spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
  application:
    name: app-backend
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true